doc/code/math.rst
doc/code/math/torch.rst
doc/conf.py
doc/requirements.txt

**Context:**
Readthedocs requires `torch` to build, which is not a strict requirement for Mr Mustard.
Removes `math/torch.py` from doc, since the module is still "under construction".
**Benefits:**
Readthedocs should build.
None
None

Remove `torch` from docs

---

doc/conf.py

**Context:** The doc colors are inherited from SF and do not match the MM logo
**Description of the Change:** change the colors to match the MM logo
**Benefits:** Matches!
**Possible Drawbacks:** Potentially could be tweaked slightly? Also, the favicon also needs to still be modified.
**Related GitHub Issues:** n/a

Update documentation colours

---

requirements-dev.txt

**Context:**
Both Tensorflow and pylint require different versions of `typing-extensions` leading to conflict when installing from unpinned `requirements-dev.txt`.
This PR pins package versions on `requirements-dev.txt` and solves the dependency conflict.
**Benefits:**
Smoot installation of packages for development.
Will use `pylint==2.10.0` which is not the latest release.

Pin `requirements-dev`

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

**Context:**
[Github issue templates](https://gh-community.github.io/issue-template-feedback/welcome/) are used on this repo to report bugs and request new features. This templates are in beta version and constantly change the API.
The latest version of the template requires the `label` field to be present on checkboxes
**Benefits:**
Fixes broken bug report and feature request forms.

Fix issue template

---

LICENSE
mrmustard/logger.py
tests/test_logger.py

**Context:**
Modules on Mr Mustard use  `print` statements instead of a `logger` that is configurable by the user.
This PR implements a logger to be used on Mr Mustard
**Benefits:**
`print` statements are not configurable by users whereas `logger` can be configured by the application using Mr Mustard.

Implement `logger`

---

.github/ISSUE_TEMPLATE/bug_report.yaml
mrmustard/math/math_interface.py
mrmustard/math/tensorflow.py

**Context:**
All backends must implement and adhere to signatures on `MathInterface`
Modifies the signature of methods on `TFmath` and some of `MathInterface` abstract methods so that both the tensorflow and torch backend adhere to `MathInterface`.
**Benefits:**
Consistent implementation of backends

Make `TFMath` adhere to signatures on `MathInterface`

---

mrmustard/utils/training.py

**Context:**
When running a `for` loop that is iterating over the `Optimizer` sending a `KeyboardInterrupt` signal (e. g., `ctrl/cmd + c`) does not stop the program execution but only the current iteration of the loop.
The execution will gracefully stop, meaning no traceback will be printed to the user. To do this a helper class `StopExecution` inheriting from `Exception` is implemented overriding the `_render_traceback_` method in order not to print a traceback.
**Benefits:**
`ctrl/cmd + c` while on a optimization loop stops the execution of the program.
This will not restore the parameters to the previous values, i. e. the values before any optimization step was performed. 
**Related GitHub Issues:** 
Resolves #104

Stop optimizer execution on `KeyboardInterrupt`

---

tests/test_logger.py

**Context:**
A logger was implemented on Mr Mustard on PR #107 following strawberry fields logger implementation. As discovered on strawberry fields, logger tests had side-effects on the logger configuration hence making tests that use the logger fail if they are executed after `test_logger`.
In specific, `test_logging_handler_defined` was setting `logger.propagate = False` meaning that messages are not passed to the handlers of ancestor loggers (see logger [docs](https://docs.python.org/3/library/logging.html#logging.Logger)). This in turn implied that, if no handlers were set for the specific logger, no message would be emitted hence making tests that check for output messages fail.
This PR incorporates the same changes applied on PR _fix failing logger …

fix logger test side effects

---

mrmustard/physics/gaussian.py
requirements-dev.txt
tests/conftest.py
tests/random.py
tests/test_lab/test_detectors.py
tests/test_lab/test_gates_fock.py
tests/test_physics/test_fock/test_fock.py

**Context:**
Black has been updated to v22.1.0 which changes the way the power operators should be styled:
`a ** b` should now be formatted as `a**b`.
All spaces around the power operator are removed (along with at least one other minor change).
**Benefits:**
The formatting check now passes with the latest version of Black.
None
None

Run latest Black version

---

.github/CHANGELOG.md
mrmustard/lab/states.py
tests/test_lab/test_detectors.py
tests/test_lab/test_states.py

**Context:**
`Homodyne(modes=[m],...)` and `Heterodyne(modes=[m],...)` should apply a detector to modes `m`.
- `modes` kwarg is added to `State.__init__` in `Homodyne`
- adds `modes` kwarg to `Coherent` on `Heterodyne`
- test detectors are applied to correct modes
- test using `modes` kwarg or `__getitem__` give consistent results 
**Benefits:**
Setting state/detector modes using `modes` kwarg or `__getitem__` give consistent results.
None
Closes #110

set `State` modes with `kwargs` and `__getitem__`

---

mrmustard/physics/fock.py

**Context:**
Tensors do not support indexed/slicing with generators
Use lists instead of generators for list of indices
**Benefits:**
Tensors are indexed correctly avoiding unexpected errors.
None
Fixes #116

use lists instead of generators when indexing states

---

.github/workflows/tests.yml

**Context:**
CI workflows should run when merging or pushing to `main` branch.
CI workflow files are pointing to the non-existent ref `master`. This PR changes `master` to `main` wherever referenced.
**Benefits:**
`main` branch code is tested whenever a merge or a push happens.

CI on master branch

---

.github/CHANGELOG.md
mrmustard/__init__.py
mrmustard/lab/gates.py
mrmustard/lab/states.py
mrmustard/math/math_interface.py
mrmustard/utils/training.py
tests/test_utils/test_opt.py

**Context:**
It would be nice to have a trainable *real* interferometer (i.e. one that doesn't mix q and p)
I added a new gate: `RealInterferometer`
**Benefits:**
We have it now :)
None
None

Real interferometer

---

requirements.txt

**Context:**
Breaking change in protobuf v4.21.0-rc1 [breaks ](https://github.com/protocolbuffers/protobuf/issues/10051) `import tensorflow`.
This PR bumps Tensorflow version to use a [release](https://github.com/tensorflow/tensorflow/releases/tag/v2.9.1) that has an upper bound for `protobuf` in Tensorflow's `setup.py`. This is a hotfix from tensorflow and the version should be updated as soon as there is a new release.
**Benefits:**
Avoid errors coming from protobuf latest version.
None
None

Bump tensorflow version (protobuf hotfix)

---

.github/CHANGELOG.md
mrmustard/training/parametrized.py

**Context:**
`State` instances contain tensors as variables (for example, the symplectic or covariance matrix of the state). States being also instances of `Parametrized` are recursed to obtain the trainable and constant parameters.
This PR substitutes the recurrence check from `Iterable` to `Sequence`. This specific logic branch is targeted for objects that contain lists (hence a `Sequence`) of Parametrized instances, like a circuit. Since tensors are also instances of `Iterable`, every object containing a tensor as a variable will be recursed but will result in an error.
**Benefits:**
Resolves the bug
```pycon
>>> SqueezedVacuum(r=1.0).constant_parameters 
TypeError: Cannot iterate over a scalar tensor.
>>> SqueezedVacuum(r=1.0).trainable_parameters …
```

Check for `Sequence` instead of `Iterable` on parameter extraction

---

tests/test_physics/test_fock/test_fock.py

This PR sets the absolute tolerance of the assertion on `test_dm_to_ket`.

[hotfix] fix failing `test_dm_to_ket`

---

.github/CHANGELOG.md
mrmustard/math/math_interface.py
tests/test_lab/test_gates_fock.py

**Context:**
The transposition operation from the math module reverses all indexes by default.
```python
math.transpose(M[[1,2,3,4]]) = M[[4,3,2,1]]
```
This is not the desired behaviour when calculating the hermitian conjugate of an operator — because the function `math.dagger` uses `math.transpose` with default args under the hood meaning the result is incorrect. Currently,
```python
math.dagger(M[[1,2,3,4]]) = math.conjugate(math.transpose(M[[1,2,3,4]])) = math.conjugate(M[[4,3,2,1]])
```
To fix the issue, the dagger operation now swaps the 1st and 2nd half of indices of a tensor as is expected for a transposition on the dagger operation. Now,
```python
math.dagger(M[[1,2,3,4]]) = math.conjugate(M[[3,4,1,2]])
```
**Benefits:**
Appropriate dagger …

bugfix - hermitian conjugate 🐛

---

mrmustard/training/optimizer.py
tests/test_training/test_opt.py

**Context:**
Mr Mustard optimizer can optimize gate parameters but not values directly defined in the backend.
This PR allows the optimizer to keep track of variables directly defined in the backend, for example
```python
from mrmustard.lab import Dgate, Sgate, Attenuator, Vacuum, Coherent, SqueezedVacuum, Rgate
from mrmustard.physics import fidelity
from mrmustard.training import Optimizer
from mrmustard.math import Math; math = Math()
import numpy as np
rotation_angle = np.pi/2
target_state = SqueezedVacuum(r=1.0, phi=rotation_angle)
r_angle = math.new_variable(0, bounds = (0, np.pi), name='r_angle')
S = Sgate(r = 0.1, phi=0, r_trainable = True, phi_trainable=False)
def cost_fn_sympl():
state_out = Vacuum(1) >> S >> Rgate(angle = r_angle)
return 1 - …
```

Include backend variables in optimization

---

mrmustard/lab/abstract/__init__.py
mrmustard/lab/abstract/measurement.py
mrmustard/lab/abstract/state.py
mrmustard/lab/detectors.py
mrmustard/physics/gaussian.py
mrmustard/utils/homodyne.py
tests/test_lab/test_detectors.py

**Context:**
An abstract base class for measurements is implemented.
**Note**: not yet implemented for fock measurements
This is the diagram of the abstraction:
```mermaid
classDiagram
Measurement <|.. Generaldyne
Measurement <-- FockMeasurement
class Measurement{
+num_modes
+postselected
+outcome
-_measure_gaussian(State other)
-_measure_fock(State other)
~primal(State other)
~__lshift__(State other)
~__getitem__(List~int~ modes)
}
class Generaldyne{
+State state
+outcome
~primal(State other)
-_measure_gaussian(State other)
-_measure_fock(State other)
}
class FockMeasurement{
(Not Integrated yet)
}
Generaldyne <|.. Homodyne
Generaldyne <|.. Heterodyne
Generaldyne *-- State
class Homodyne{
+State state
-_measure_gaussian(State other)
-_measure_fock(State …
```

Implement `Measurement` abstract class 📊

---

.github/CHANGELOG.md
mrmustard/lab/gates.py
mrmustard/math/math_interface.py
mrmustard/math/tensorflow.py
tests/test_lab/test_gates_fock.py
tests/test_physics/test_fock/test_fock.py

**Context:**
[The Walrus PR #351](https://github.com/XanaduAI/thewalrus/pull/351) implemented a more stable calculation of the displacement unitary.
The `Dgate` now uses The Walrus to calculate the unitary and gradients of the displacement gate.
Before:
After:
**Benefits:**
This provides better numerical stability for larger cutoff and displacement values.
None
None

Calculate displacement operator unitary matrix using The Walrus

---

mrmustard/math/math_interface.py
mrmustard/math/tensorflow.py

------------------------------------------------------------------------------------------------------------
**Context:**
Math interface
Adds `eye_like` function, which returns the identity matrix to match the shape and dtype of the argument.
**Benefits:**
Simpler to get the identity of the right size and dtype
Not standard
None

adds eye_like function to interface and tf backend

---

.github/CHANGELOG.md
mrmustard/utils/graphics.py
mrmustard/utils/wigner.py
tests/test_utils/test_wigner.py

**Context:**
Calculation of the Wigner function is already included in Mr Mustard but hidden in the graphics module
This PR moves the Wigner function calculation to its own module and numbifies it.
**Benefits:**
Now you can calculate the Wigner function using
```python
from mrmustard.utils.wigner import wigner_discretized
wigner_discretized(dm, q, p) # dm is a density matrix
```
It should be faster as well because it uses numba jit.
None

Refactor Wigner function into module

---

mrmustard/__init__.py
mrmustard/math/__init__.py
tests/test_math/test_interface.py

**Context:**
settings are not easy do discover
the settings object has now a nice repr
**Benefits:**
users can see al the settings at once
None I can think of
None

settings repr

---

.github/CHANGELOG.md
mrmustard/lab/abstract/state.py

**Context:**
norm is confusing field in the repr of `State` (it's the sqrt of the probability if the state is pure and the probability if it's mixed).
Replace norm with probability 
**Benefits:**
Consistent meaning and also more practically useful
some users may miss the good old norm?

changes norm to probability in repr of State

---

.github/CHANGELOG.md
.github/workflows/changelog.yml

**Context:**
Always forgetting to add entries to the CHANGELOG file?
Now github will remind you to do so — this PR implements a new CI workflow checking if an entry has been added to the CHANGELOG file. This check is not mandatory meaning it won't block the ability to merge the PR, however checks will appear as failed. In case no changelog entry is needed one can use the `no changelog` label to disable the check.
This PR also adds the changelog entry for PR #188.
**Benefits:**
No more PRs without CHANGELOG entries
None

Check if changelog entry is created on PRs

---

.github/CHANGELOG.md
.github/workflows/tests.yml
.pylintrc
doc/code/training.rst
doc/code/training/trainer.rst
mrmustard/training/trainer.py
setup.py
tests/test_training/test_trainer.py

**Context:**
Adds `map_trainer` as the interface for distributing optimization workflows using ray so that things can happen in parallel -- replacing the need for `for` loops.
_Code here has been personally looked at by Trudeau._
Demo notebook in recipes.
Documentation page for the `trainer` module is added with some examples, which is also in the docstring of `map_trainer` so that it can be conveniently read in Jupyter directly with shift+tab.
I've also had some weird problem with the unit tests (all passing locally) running on github action where some times it would just hang. I've tried removing my new tests one by one and adding them back again one by one, and it somehow worked at the end... I changed the testing workflow file with direct `pip install …

Adds ray-based distributed trainer.

---

.github/CHANGELOG.md
mrmustard/__init__.py
mrmustard/lab/abstract/state.py
mrmustard/physics/fock.py
tests/test_lab/test_detectors.py
tests/test_lab/test_gates_fock.py

**Context:**
autocutoffs are a bit flimsy, it would be nice to have a norm-based autocutoff
Uses Robbe's new function to improve autocutoff: each mode now gets a cutoff such that if it were the marginal it would capture `settings.AUTOCUTOFF_PROBABILITY` probability (default 0.999).
**Benefits:**
Much more sensible autocutoffs
Some users may need to update their code
perhaps [#118](https://github.com/XanaduAI/MrMustard/issues/118)

Improved autocutoff

---

.github/CHANGELOG.md
mrmustard/training/parametrized.py

**Context:**
negative parameters were showing a 0 instead of the minus sign.
Fixes this issue
**Benefits:**
Correct parameters!
None
None

displays sign correctly

---

.github/CHANGELOG.md
mrmustard/lab/states.py
tests/test_lab/test_gates_fock.py

**Context:**
When projecting onto Fock the autocutoff doesn't check the photon number of the Fock projection. Thanks to Jacob for spotting it.
Now it does. Added a test too.
**Benefits:**
No unnecessary cutoff errors when projecting onto a Fock state
None
None

bugfix, test and changelog entry

---

.github/CHANGELOG.md
mrmustard/math/numba/compactFock_1leftoverMode_amps.py
mrmustard/math/numba/compactFock_1leftoverMode_grad.py
mrmustard/math/numba/compactFock_diagonal_amps.py
mrmustard/math/numba/compactFock_diagonal_grad.py
tests/test_math/test_compactFock.py

**Context:** There was a bug in the algorithms for faster PNR sampling from Gaussian circuits using density matrices. In the case where the cutoff of the first detector was equal to 1, the resulting density matrix was incorrect.
**Description of the Change:** The problem was solved by allowing for diagonal pivots to be used when the cutoffs[0]=1, effectively changing line 4 of Algorithm 1 in https://arxiv.org/pdf/2303.08879.pdf from `if diag_1 < C_1 − 1 then` to `if (diag_1 < C_1 − 1) or (C_1==1) then`.

Compact fock correction

---

mrmustard/lab/abstract/state.py
mrmustard/lab/abstract/transformation.py
mrmustard/lab/gates.py
mrmustard/math/tensorflow.py
mrmustard/physics/fock.py
tests/test_physics/test_bargmann.py
tests/test_training/test_opt.py

**Context:**
The `more_strategies` PR introduced several custom gradients, but we never noticed they were broken under some conditions.
- Gradients are now cast to the backend array type
- This PR also adds the numpy option to the bargmann methods
**Benefits:**
Gradients work
None
None

Bugfix gradients

---

.github/CHANGELOG.md
pyproject.toml

* Optimization callback functionalities has been improved. A dedicated `Callback` class is added which
is able to access the optimizer, the cost function, the parameters as well as gradients, during the
optimization. In addition, multiple callbacks can be specified. This opens up the endless possiblities
of customizing the the optimization progress with schedulers, trackers, heuristics, tricks, etc.
[(#219)](https://github.com/XanaduAI/MrMustard/pull/219)
* Tensorboard-based optimization tracking is added as a builtin `Callback` class: `TensorboardCallback`.
It can automatically track costs as well as all trainable parameters during optimization in realtime.
Tensorboard can be most conveniently viewed from VScode.
[(#219)](https://github.com/XanaduAI/MrMustard/pull/219)
```python
import …
```

Release v050

---

.github/CHANGELOG.md
mrmustard/utils/misc_tools.py
tests/mock_classes/general_mocks.py
tests/test_utils/test_misc_tools.py

**Context:**
Within the representations project, some tools were needed.
Implement a duck-style type-checker and a very generic factory method.
**Benefits:**
Allowing to check whether an object is of a certain class in a more pythonic way than `isinstance`. Allowing the creation of objects in tests (and beyond) through a dedicated factory.
The current implementation of the duck type checker doesn't support checking python native types like booleans or ints, floats.

Utils for the Representations stage1 MVP

---

.github/CHANGELOG.md
mrmustard/lab/gates.py
mrmustard/math/math_interface.py
mrmustard/math/tensorflow.py
tests/test_lab/test_gates_fock.py

**Context:**
We add the phase noise gate. This will convert a state to the Fock representation, as the phase noise isn't a Gaussian operation. Note that this isn't an approximation of the channel: it's exact.
We add the `PhaseNoise` gate, available under `mrmustard.lab.gates`
**Benefits:**
It's now possible to implement a realistic phase noise :)
None
None

New phase noise

---

.github/CHANGELOG.md
mrmustard/lab/abstract/state.py
mrmustard/lab/gates.py
mrmustard/lab/states.py
mrmustard/physics/__init__.py
mrmustard/physics/fock.py
mrmustard/physics/gaussian.py
mrmustard/utils/graphics.py
mrmustard/utils/wigner.py
tests/test_lab/test_detectors.py
tests/test_lab/test_states.py
tests/test_physics/test_fidelity.py
tests/test_physics/test_fock/test_fock.py
tests/test_physics/test_gaussian/test_symplectics.py
tests/test_training/test_opt.py

Please complete the following checklist when submitting a PR:
If you've fixed a bug or added code that should be tested, add a test to the
test directory!
If you do make documentation changes, make sure that the docs build and
render correctly by running `make docs`.
<filename>` on any relevant files. You will need to have the Black code format installed:
`pip install black`.
change, and including a link back to the PR.
[PEP8 standards](https://www.python.org/dev/peps/pep-0008/) except line length.
We check all of our code against [Pylint](https://www.pylint.org/).
To lint modified files, simply `pip install pylint`, and then
run `pylint mrmustard/path/to/file.py`.
When all the above are checked, delete everything above the dashed
line and fill in the pull request template. …

Ensuring that hbar can only be specified in `Settings`

---

.github/CHANGELOG.md
poetry.lock
pyproject.toml

**Context:**
Relaxes dependency versions in pyproject.toml.
**Benefits:**

Relaxes scipy

---

.github/CHANGELOG.md
pyproject.toml

**Context:**
Includes julia dependency files into the python packaging so that MM's downstreams can reproduce julia installation without cloning the repo.
- adds `julia_pkg` to the `include` in pyproject.toml, which acts like the old MANIFEST
- removes `pyproject.toml` from includes which is not needed and pollutes the site-packages in the installation.
**Benefits:**

include julia_pkg in python packaging

---

.github/CHANGELOG.md
mrmustard/_version.py
pyproject.toml

**Context:**
Currently MM's `__version__` depends on loading (and thus the existence of) the pyproject.toml file, but the version info is already present in the python package.
Exclusion of pyproject.toml in #303 is causing the __version__ to break in downstream installations. Instead of reverting back to including the pyproject toml, this PR addresses the issue by fundamentally fixing it.
Switches from tomli loading of pyproject toml to get version to using importlib.metadata.
**Benefits:**
the pyproject.toml is no longer thrown into the `site-packages` folder when installing MM.

Use importlib for version

---

.github/CHANGELOG.md
mrmustard/physics/gaussian.py

**Context:** The documentation of loss_XYd and amp_XYd is not correct, which are used to define two Gaussian channels: Attenuator and Amplifier.
**Description of the Change:** Change the wrong definition in the document part of both functions.
**Benefits:**

fix the document about functions loss_XYd and amp_XYd

---

.github/CHANGELOG.md
mrmustard/math/backend_numpy.py
mrmustard/math/backend_tensorflow.py
mrmustard/physics/fock.py

Removes ``ComplexWarning`` at the root (inside the backend) rather than in the functions that require casting

Remove warnings at the root

---

.github/CHANGELOG.md
mrmustard/math/backend_manager.py
mrmustard/math/backend_numpy.py
mrmustard/math/backend_tensorflow.py
mrmustard/math/lattice/steps.py
mrmustard/math/lattice/strategies/compactFock/diagonal_amps.py
mrmustard/math/lattice/strategies/compactFock/inputValidation.py
mrmustard/math/lattice/strategies/vanilla.py
tests/test_math/test_lattice.py

**Context:** Add multiple functions to make recursive functions work with batch dimension.
**Description of the Change:** We add batch with hermite_renormalized vanilla version and hermite_renormalized_diagonal version in Numba.
**Benefits:** Gain speed when we have a batch in b of the triple(A,b,c).

Add batch in recursive relation

---

.github/CHANGELOG.md
mrmustard/math/lattice/strategies/compactFock/diagonal_amps.py
mrmustard/math/lattice/strategies/compactFock/helperFunctions.py
mrmustard/math/lattice/strategies/compactFock/singleLeftoverMode_amps.py
tests/test_lab/test_detectors.py

`np.empty` returns an array of given shape and type, without re-initializing its values.
This means that the array's entries are not zeros (they are equal to whatever was in memory before that memory slot became part of the returned array).
This creates instabilities in some of the hermite renormalized methods.
For this reason, we are switching to `np.zeros`

Switching from `np.empty` to `np.zeros`

---

tests/test_math/test_compactFock.py

**Context:**
The tests in `tests/test_math/test_compactFock.py` take a long time to run (over 5mins with the tensorflow backend) and are very intensive in terms of memory. They often crash on GitHub, making our entire workflow unstable.
This PR simplifies `tests/test_math/test_compactFock.py` so that the tests in it are less intensive in time (1min50s) and memory, but still test all that they were originally testing.

Simplifying tests for compact fock file

---

.github/CHANGELOG.md
mrmustard/math/lattice/strategies/vanilla.py

Same change as for `vanilla()`: The returned nD tensor is flattened, manipulated as a 1D tensor, and finally reshaped

Speeding up `vanilla_vjp`

---

mrmustard/math/backend_tensorflow.py
mrmustard/training/callbacks.py

**Context:**
The previous solution based on `logging` does not appear to work on every OS

Removing TF warnings on import with `os` instead of `logging`

---

mrmustard/math/backend_manager.py
mrmustard/math/backend_numpy.py
tests/test_lab/test_detectors.py
tests/test_math/test_backend_manager.py

**Context:**
```
probs = np.array([1e-6 for _ in range(300)])
results = [math.Categorical(probs, "") for _ in range(100)]
assert len(set(results)) > 1
```
When using the numpy backend, the code above fails: `results` contains 100 identical values.
This is because `math.Categorical` uses `np.random.multinomial`, which assumes that the probabilities sum up to `1` (if not, the last probability is increased such that the resulting probabilities sum up to `1`)

Fix `math.Categorical`

---

mrmustard/physics/triples.py
tests/test_physics/test_triples.py

**Context:** Bug fix of the triples for attenuator
**Description of the Change:** c=1.0 for attenuator
**Benefits:**

fix the c of the attenuator triples needs to be 1

---

.github/CHANGELOG.md
mrmustard/lab/abstract/transformation.py
mrmustard/physics/bargmann.py
mrmustard/physics/gaussian.py
tests/test_lab/test_detectors.py
tests/test_lab/test_state.py

**Context:** There are three bugs fixed in this PR.
1. the projection onto the Vacuum state will use the generaldyne where the projection function is not correct.
For example,
`from mrmustard.lab import *;Vacuum(3) << Vacuum(3)`
The projection in the example above is not 1.0, which should be 1.0.
This has been fixed by changing the functions inside generaldyne.
3. add more text to explain about complex_gaussian_integral and other function in bargmann.py.
4. fix the problems that the state will be reassigned during the running of the circuit.
For example,
`from mrmustard.lab import *;
vac0 = Vacuum(1);
d1 = Dgate(0.1, 0.1);
vac0 >> d1;
vac0.bargmann()`
the state `vac0` state will be modified after going through the first Dgate, which is not the behaviour we want.
**Description of the …

Fix the small bugs

---

.devcontainer/Dockerfile
.github/workflows/builds.yml
.github/workflows/format.yml
.github/workflows/tests_docs.yml
.github/workflows/tests_numpy.yml
.github/workflows/tests_tensorflow.yml
.github/workflows/upload.yml
.readthedocs.yml
poetry.lock
pyproject.toml

**Context:**
When `poetry` is used to install Mr Mustard and its dependencies, a package called `wrapt` is installed in an outdated version `1.12.1`. When importing `tensorflow`, this outdated version causes an import error.
This did not show up on SisterPam, because `pip install mrmustard` installs a different set of dependencies
The current version of pylint requires `wrapt < 1.13`. Bumping it up allows `wrapt` to be installed in a more recent (though not the most recent) version.
I also update the tests files, so that they now test python 3.11

Updating `pylint` in order to bump `wrapt`

---

mrmustard/lab_dev/states/base.py
mrmustard/lab_dev/transformations/base.py
tests/test_lab_dev/test_states.py

**Context:**
```
from mrmustard.lab_dev import Coherent
Coherent([0, 1]) >> Coherent([0]).dual
```
At the moment, the code above returns a `CircuitComponent`. We want it to return a `Ket`.

Better type handling for `rshift`s

---

mrmustard/physics/triples.py
tests/test_physics/test_triples.py

**Context:**
One more useful triple
A new function in physics/triples.py and a test
**Benefits:**
Can break down the 4-wired attenuator into two 3-wired tensors
None
None

Added attenuator kraus Abc triple

---

.github/workflows/tests_numpy.yml
.github/workflows/tests_tensorflow.yml
.readthedocs.yml
Makefile

- `Makefile` syntax requires tabs, not spaces, so this `make` target didn't work
- Sphinx inheritance diagrams require the RTD builder machine to have `graphviz` installed. Otherwise, [it doesn't work](https://mrmustard.readthedocs.io/en/stable/code/training.html#class-inheritance-diagram)
- it's [fixed](https://mrmustard--387.org.readthedocs.build/en/387/code/training.html#class-inheritance-diagram) by this PR
- run numpy and tensorflow tests unconditionally

fix inheritance diagrams and make install

---

.github/CHANGELOG.md
mrmustard/math/backend_manager.py
mrmustard/math/backend_numpy.py
mrmustard/math/backend_tensorflow.py
mrmustard/physics/gaussian.py

The failure listed below was due to the symplectic eigenvalue code randomly returning the same symplectic eigenvalue multiple times.  This occured because it was assumed that the computed eigenvalues of the operator |iΩΣ| were sorted.  This assumption is not true for all cases.
This fix ensures that the eigenvalues of the operator are sorted so that the assumption is true and the symplectic eigenvalues are indeed every second entry.  The test_random_state_is_entangled test always passes with this fix.
```
================================== FAILURES ===================================
_______________________ test_random_state_is_entangled ________________________
def test_random_state_is_entangled():
"""Tests that a Gaussian state generated at random is entangled."""
state = Vacuum(2) >> …
```

Fix the computation of symplectic eigenvalues

---

.github/CHANGELOG.md
mrmustard/math/backend_tensorflow.py
poetry.lock
pyproject.toml
tests/test_math/test_backend_manager.py

**Context:**
If you install MrMustard with `pip`, it will install the latest tensorflow, but that does not allow the use of `tf.keras.optimizers.legacy.Adam`. We need the non-legacy version, but it's [slow on M1/M2 Macs](https://stackoverflow.com/questions/77222463/is-there-a-way-to-change-adam-to-legacy-when-using-mac-m1-m2-in-tensorflow). Some manual effort is required to support the legacy optimizer with TF 2.16+, and it seems out of the door anyway. I'd advise Mac M1/M2 users to install TF 2.15 in advance if they want the better optimizer for them (until TF fixes it, at least).
- Add the `tf` extra to `tensorflow-probability`. This one's a bit hacky, because that extra doesn't exist until 0.24+, but if you are using 0.24+ (which you would be with a `pip …

enable new TF and pip installation

---

.github/CHANGELOG.md
.github/workflows/scripts/visualize_timings.py
mrmustard/lab_dev/states/base.py
tests/conftest.py

**Context:**
The drawing tool is not very useful today, so I touched it up a bit by adding `plotly` support.
1. Skip all `test_training` tests when using `numpy` because they do nothing
2. Add the `plotly` and `plotly-grouped` modes to the test visualizer because it's much better
3. filter out `test_about` and any tests that always return 0.0 (in other words, that always finish in 50ms or less) because we can't get anything useful from that
**Benefits:**
- Easier to glean some information from the visualizer
- No time wasted running silly numpy tests that do nothing
N/A
<details>
<summary>How to use it (from a notebook)</summary>
```
!aws s3 sync s3://<top-secret-bucket-name>/ /some/path/you/choose/
%run …
```

skip training on numpy, improve drawing

---

Makefile
mrmustard/lab_dev/transformations/base.py
tests/test_lab_dev/test_transformations.py
tests/test_math/test_backend_manager.py

**Context:**
`Transformation`'s `inverse()` method numerically computes the inverse. We can avoid this on `Unitary` by calling `self.dual`.
`Unitary` now overrides `inverse()` to call `self.dual`. Additionally, small formatting changes are included and a fix to the Makefile.

Unitary override inverse 

---

mrmustard/lab_dev/circuit_components.py
mrmustard/math/tensor_networks/networks.py
mrmustard/physics/ansatze.py
mrmustard/physics/representations.py
tests/test_lab_dev/test_circuit_components.py
tests/test_math/test_tensor_networks/test_networks.py

**Context:** A small cleanup PR.
**Description of the Change:** 
- Minor documentation updates/ formatting for consistency. 
- Removed `__getattr__` on `CCView` as it can cause undocumented behaviour.
- Added a `block` option on `draw` such that blocking plots do not display when running the testing suite. 
- Some unnecessary calls to `math.astensor` 
- Moved the batched array logic from `Fock` to `ArrayAnsatz`

Minor cleanup to some docstrings + miscellaneous 

---

mrmustard/physics/triples.py

**Context:** Some calls in triples.py were relying on a call to `tf.experimental.numpy.experimental_enable_numpy_behavior()` when using a tensorflow backend. This would only be triggered when calling `math.kron`. As a result, the full test suite would pass but individual tests would fail.
**Description of the Change:** Changed some `.reshape` calls to `math.reshape`.

Fixes to triples.py

---

mrmustard/lab_dev/circuit_components.py
mrmustard/lab_dev/states/base.py
mrmustard/math/backend_tensorflow.py
mrmustard/physics/ansatze.py
tests/test_lab_dev/test_states.py

`Ket` and `DM` now have a method `normalize()` which returns a normalized version of the state (prob = 1)

Added methods and test for `normalize()`

---

mrmustard/lab_dev/states/base.py
mrmustard/lab_dev/states/quadrature_eigenstate.py
mrmustard/physics/gaussian_integrals.py
tests/test_lab_dev/test_states/test_quadrature_eigenstate.py

**Context:** QuadratureEigenstate `__repr__` currently fails due to an L2 norm calculation. Solution is to override the L2_norm. Additionally, set manual shape on QuadratureEigenstate for visualization purposes. 
**Description of the Change:** L2_norm on QuadratureEigenstate returns np.inf, manual_shape is set to (50,), some additional cleanup.

QuadratureEigenstate Fixes 

---

mrmustard/physics/ansatze.py
mrmustard/physics/representations.py
tests/test_physics/test_ansatz.py

**Context:** Dunder methods on ArrayAnsatz such as `__add__` currently fail if the shapes of the arrays do not match (e.g. adding a `(1, 2, 2)` and a `(1, 3, 3)` array). This PR includes calls to reduce in these dunder methods exploiting the fact we can just pad the smaller array with zeros making them compatible.
**Description of the Change:** `reduce` has been moved to `ArrayAnsatz` and `__add__`, `__mul__` and `__truediv__` make use of calls to `reduce`. Additionally, some cleanup such as reordering methods alphabetically. 
**Benefits:** Interactions between ArrayAnsatz of different fock cutoffs are more flexible

Move reduce to ArrayAnsatz and include calls in dunder methods

---

.github/CHANGELOG.md
mrmustard/lab_dev/states/base.py
mrmustard/physics/fock.py
mrmustard/widgets/__init__.py

**Context:**
Now that the visualization improvements have been added to MrMustard, there's some feedback that needs addressing. This PR does that.
- Change the default colour scheme in the 2D/3D Wigner plots from `viridis` to `RdBu` to distinguish from the density matrix plot as suggested in #418. I definitely agree with the choice - negative is red, zero is white, and positive is blue. Felt semi-intuitive. If you'd prefer another one from [plotly's list](https://plotly.com/python/builtin-colorscales/), lmk!
- Force the mid-point of the colour axis in those Wigner plots to always be 0 instead of auto-scaling, and show the scale
- Change the widget in the Fock repr to be kinda-square
- Change the 2D Fock magnitude plot to be a bar graph
**Benefits:**
- Things …

Various improvements for visualizations

---

mrmustard/utils/settings.py

you can't type-hint with `|` in python 3.9, so I'm righting my wrong

fix type hint for python 3.9

---

mrmustard/lab_dev/states/number.py
tests/test_lab_dev/test_states/test_number.py

**Context:** This PR fixes a bug where `manual_shape` on `Number` could be a tensorflow object rather than an `int` causing issues.
**Description of the Change:** `int(cutoff)` and a test

manual_shape on Number bug fix

---

mrmustard/lab_dev/circuit_components.py
mrmustard/lab_dev/states/base.py
tests/test_lab_dev/test_states/test_states_base.py

**Context:**
Update autoshape for `ket` and `dm` if they have a polynomial.
Adding a check to see if the bargmann representation has a polynomial and set the `autoshape_max` as shape if that is the case.

Autoshape poly

---

mrmustard/lab_dev/circuit_components.py
mrmustard/physics/ansatze.py
mrmustard/physics/representations.py
tests/test_lab_dev/test_circuit_components.py

**Context:** currently on develop `to_bargmann` is not checking if original bargmann data exists leading to issues such as 
```
state = SqueezedVacuum([0], r=1.0)
dgate = Dgate([0], x=10.0).to_fock(150)
state >> dgate
```
running out of memory. 
**Description of the Change:** `to_bargmann` now checks for original bargmann data. Removed a single line that has `original_fock_data` as that is not used anywhere. Moved some things to ansatz. `__truediv__` and `__mul__` can update the original bargmann data as long as other is a scalar. `_original_bargmann_data` is renamed to `_original_abc_data`. Some `Representation` cleanup removing duplicate code.

to_bargmann() original bargmann data bug

---

.gitignore
mrmustard/lab_dev/circuit_components.py
tests/test_lab_dev/test_circuit_components.py

**Context:** After [to_bargmann() original bargmann data bug](https://github.com/XanaduAI/MrMustard/commit/667c516453df9844baa514162f737da2d762f2fa) we always store the original Bargmann data when calling to_fock. This isn't ideal in the case when c is an array where instead keeping the array is more efficient. 
**Description of the Change:** `to_fock` checks the polynomial shape and only sets `._original_abc_data` if c is a scalar
___
Bug fix, Tests
___
- Fixed a bug in `to_fock` method to conditionally store `_original_abc_data` only when `c` is a scalar.
- Added tests to ensure `_original_abc_data` is correctly set or not set based on the polynomial shape.
- Improved efficiency by avoiding unnecessary storage of data when `c` is an array.
___
<table><thead><tr><th></th><th …

Avoid storing original_abc_data when c is not a scalar 

---

mrmustard/physics/triples.py
tests/test_lab_dev/test_circuit_components_utils.py
tests/test_lab_dev/test_states/test_states_base.py
tests/test_lab_dev/test_transformations/test_cft.py
tests/test_physics/test_ansatz.py
tests/test_physics/test_triples.py

**Context:**
We would like `BtoPS` to compute the characteristic function, but it currently computes it with a `1/2pi` prefactor. 
Changing the `c` of `BtoPS` from `1/(2*pi)` back to `1` so that we can readily compute characteristic function (and propagating to tests).
**Benefits:**
Minor (we can compute characteristic function directly by BtoPS)
Need to be ware of this change when computing Wigner function (the 2pi factor would be placed there -- look at `test_cft.py` to see how to do this).
None.

c of BtoPS

---

mrmustard/utils/settings.py
tests/test_utils/test_settings.py

**Description of the Change:** Some cleanup of settings
___
enhancement, tests
___
- Added a new `MAX_BATCH_SIZE` setting to the `Settings` class in `mrmustard/utils/settings.py` with a default value of 1000.
- Cleaned up and reorganized the settings, including documentation improvements and reordering of properties.
- Implemented a property for `CACHE_DIR` with appropriate getter and setter methods.
- Refactored context management methods (`__call__`, `__enter__`, `__exit__`) for better usability.
- Added a test in `tests/test_utils/test_settings.py` to ensure the `MAX_BATCH_SIZE` default value is correctly set.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …

Cleanup MrM settings

---

mrmustard/physics/ansatze.py
tests/test_physics/test_ansatz.py

We allow making linear superpositions of components with different number of polynomial wires by padding A and b with zeros, and adding empty dimensions to the c array.
___
Enhancement, Tests
___
- Enhanced the addition operation in `ansatze.py` to pad matrices `A` and `b` when the number of polynomial wires differs, ensuring compatibility.
- Introduced a check to raise a `ValueError` if polynomial shapes are inconsistent.
- Expanded dimensions of arrays to handle different shapes during addition.
- Added tests to verify correct padding of `A` and `b` and to ensure a `ValueError` is raised for inconsistent polynomial shapes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …

adds padding when num poly wires is different

---

mrmustard/math/backend_tensorflow.py
mrmustard/physics/gaussian_integrals.py
mrmustard/physics/representations.py
mrmustard/physics/triples.py
tests/test_lab_dev/test_circuit_components_utils.py
tests/test_physics/test_gaussian_integrals.py
tests/test_physics/test_representations.py

Cleaned up and refactored Gaussian integrals, now working with batched, non batched and polynomial inputs
___
enhancement, tests
___
- Refactored Gaussian integral functions by removing deprecated functions and introducing `complex_gaussian_integral_1` and `complex_gaussian_integral_2`.
- Enhanced `join_Abc` function to support batch processing and improved input validation.
- Updated various modules to utilize the new Gaussian integral functions.
- Revised tests to cover new functionality and removed tests for deprecated functions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>gaussian_integrals.py</strong><dd><code>Refactor Gaussian integral functions and …

New broadcasted gaussian integrals

---

mrmustard/lab_dev/circuit_components.py
tests/test_lab_dev/test_circuit_components.py

**Context:** The following fails on develop:
```
rng = np.random.default_rng(seed=2334255467567)
r = [rng.random(), -rng.random()]
theta = rng.random() * 2 * np.pi
pnr_cutoff = rng.integers(1, 25)
out_loss = rng.random()
pnr_loss = rng.random()
outcome = rng.integers(0, pnr_cutoff)
mm_state = (
SqueezedVacuum([0, 1], r)
>> BSgate([0, 1], theta)
>> Attenuator([0, 1], [1 - out_loss, 1 - pnr_loss])
>> Number([1], outcome).dual
)
mm_state_dm = (
SqueezedVacuum([0, 1], r)
>> BSgate([0, 1], theta)
>> Attenuator([0, 1], [1 - out_loss, 1 - pnr_loss])
>> Number([1], outcome).dm().dual
)
assert mm_state.representation == mm_state_dm.representation
```
This is due to the permutation order of `mm_state_dm` differing to `mm_state` because of the order of matmul operations.
**Description of the …

Rshift order bugfix

---

mrmustard/lab_dev/states/base.py
mrmustard/lab_dev/states/dm.py
mrmustard/lab_dev/states/ket.py
mrmustard/lab_dev/transformations/base.py

**Context:** Noticed we can cleanup some of our class methods on `states` and `transformations`. I believe a lot of this is just remnants of the Representation refactor where now we can rely on `from_ansatz` and have `cls` handle the proper return types. 
**Description of the Change:** Some abstract methods are now defined and removed unnecessary code.

Light cleanup of class methods

---

mrmustard/lab_dev/states/dm.py
tests/test_lab_dev/test_states/test_dm.py
tests/test_lab_dev/test_transformations/test_transformations_base.py
tests/test_physics/test_wires.py

**Context:**
Currently, MM uses the non-standard ordering of wires when outputting DMs in Fock basis.
Added `MM_order` to the `from_fock` functionality of DMs so that by `MM_order = False` we get the standard convention back.
**Benefits:**
Easier for Fock manipulations. 
None.
None.

Ability to choose DM ordering of wires

---

mrmustard/math/backend_manager.py
mrmustard/math/backend_numpy.py
mrmustard/math/backend_tensorflow.py
tests/test_math/test_backend_manager.py

**Context:** Pulling out of the `BtoF_V2` branch. `atleast_nd` is a more general implementation of our `at_least1d`, `at_least2d`, `at_least3d` methods. 
**Description of the Change:** Implemented `atleast_nd` and changed `at_least1d`, `at_least2d` and `at_least3d` to be convenience methods for certain cases of `atleast_nd` 
**Benefits:** Single implementation of `atleast_nd` 
**Possible Drawbacks:** N/A

atleast_nd

---

pyproject.toml
uv.lock

**Context:** Oversight with the Jax PR is we need to restrict to python 3.10+ 
**Description of the Change:** Setting python to 3.10+. Also brought back `tensorflow-io-gcs-filesystem` 😢

Restrict to Python 3.10+

---

.github/workflows/tests_numpy.yml
.github/workflows/tests_tensorflow.yml

**Context:** When introducing Jax we bumped the minimum version of Python to 3.10 but forgot to update our workflows.
**Description of the Change:** Bumping up the min python version to 3.10 for our github workflows.

GitHub Workflow Python 3.10 Minimum

---

mrmustard/physics/ansatz/array_ansatz.py
mrmustard/physics/ansatz/polyexp_ansatz.py

**Context:**
sometimes we need a little flexibility when comparing CircuitComponents, Representations and Ansatze
the comparison operator == now supports ATOL via settings:
```python
with settings(ATOL=1e-6):
this == that
```

adds atol to allclose in ansatz

---

mrmustard/lab/states/dm.py
mrmustard/lab/states/ket.py
tests/test_lab/test_states/test_dm.py

**Context:**
There are flaky tests in our current implementations of stellar decomposition for `DM`s. Moreover, our current implementation of physical stellar decomposition on `Ket`s makes uses of `contract` which can be circumvented, and hence, improving the speed.
Addressing the issues above.
**Benefits:**
Having no flaky tests + faster decomposer
None.
None.

improved stellar decomposition

---

mrmustard/lab/states/dm.py
mrmustard/math/backend_jax.py
mrmustard/math/backend_manager.py
mrmustard/math/backend_numpy.py
mrmustard/math/backend_tensorflow.py
mrmustard/utils/settings.py

**Context:** The `optimize` parameter in `einsum` can be quite useful but our custom backend does not current support it's use.
**Description of the Change:** Took out the `optimize` changes from [mm_einsum #571](https://github.com/XanaduAI/MrMustard/pull/571). Added an `EINSUM_OPTIMIZE` setting defaulting to greedy. Fixed a bug in DM when calling fock_array with standard ordering with a linear superposition state

Adding support for `optimize` in einsum 
