XanaduAI/MrMustard

- Makefile
- doc/conf.py
- doc/development/development_guide.rst
- doc/development/research.rst
- doc/index.rst
- doc/introduction/basic_reference.md
- mrmustard/README.md
- mrmustard/__init__.py
- mrmustard/lab/abstract/measurement.py
- mrmustard/lab/abstract/state.py
- mrmustard/lab/abstract/transformation.py
- mrmustard/lab/detectors.py
- mrmustard/lab/gates.py
- mrmustard/lab/states.py
- mrmustard/math/__init__.py
- mrmustard/math/math_interface.py
- mrmustard/math/tensorflow.py
- mrmustard/physics/__init__.py
- mrmustard/physics/fock.py
- mrmustard/physics/gaussian.py
- mrmustard/utils/parametrized.py
- mrmustard/utils/training.py
- mrmustard/utils/xptensor.py
- tests/test_about.py
Tidying up some docstrings and left-over `Mr. Mustard` (should be `Mr Mustard`)
> Tidy up docs and typos

- mrmustard/math/math_interface.py
- mrmustard/utils/training.py
- Adds citations for symplectic and orthogonal optimization
- fixes variable/function names to match math
> Add citation

- README.md
- mrmustard/math/math_interface.py
- mrmustard/utils/training.py
Correcting the indentation of doc strings
> Add citation again

- .github/CHANGELOG.md
- doc/index.rst
Adds contributors to first release.
> Add contributors

- .github/CHANGELOG.md
- mrmustard/_version.py
> Increment version number to 0.1.1

- .pylintrc
- mrmustard/lab/abstract/__init__.py
- mrmustard/lab/abstract/measurement.py
- mrmustard/lab/abstract/state.py
- mrmustard/lab/abstract/transformation.py
- mrmustard/lab/circuit.py
- mrmustard/lab/detectors.py
- mrmustard/lab/gates.py
- mrmustard/lab/states.py
- requirements-dev.txt
- tests/test_physics/test_fock/test_fock.py
- tests/test_utils/test_opt.py
**Context:**
Mr Mustard strives to comply with PEP8 standards for code quality.
- This PR refactors the module `lab` so that `pylint mrmustard/lab` code rating goes from `-0.84/10` to `9.82/10`. 
- Some other refactors have been applied to ease code readability and maintenance.
- A couple of new docstrings are included.
**Benefits:**
Code quality of `lab` module is improved.
> Improve code quality of `lab` module

- mrmustard/math/__init__.py
- mrmustard/math/autocast.py
- mrmustard/math/math_interface.py
- mrmustard/math/tensorflow.py
- mrmustard/math/torch.py
**Context:**
Mr Mustard uses `pylint` for code quality checking.
- This PR refactors the module `math` so that `pylint mrmustard/math` code rating goes from `1.45/10` to `9.09/10`. 
- A couple of new docstrings are included.
**Benefits:**
Pylint score of `math` module is improved.
> Improve pylint score of `math` module

- mrmustard/physics/__init__.py
- mrmustard/physics/fock.py
- mrmustard/physics/gaussian.py
**Context:**
Mr Mustard uses `pylint` for code quality checking.
- This PR refactors the module `physics` so that `pylint mrmustard/physics` code rating goes from `6.65/10` to `9.89/10`. 
- A couple of new docstrings are included.
**Benefits:**
`pylint` score of `physics` module is improved.
> Improve pylint score of `physics` module

- mrmustard/__init__.py
- mrmustard/types.py
- mrmustard/utils/graphics.py
- mrmustard/utils/parametrized.py
- mrmustard/utils/training.py
- mrmustard/utils/xptensor.py
**Context:**
Mr Mustard uses `pylint` for code quality checking.
This PR refactors code pieces that were not touched by other `pylint-*` PRs, leaving Mr Mustard with an overall high score when running `pylint`.
**Benefits:**
Mr Mustard code quality score is above 9 points on `pylint`.
> Improve pylint score of Mr Mustard

- .github/CHANGELOG.md
- README.md
- doc/introduction/basic_reference.md
**Context:**
Mr Mustard API has changed since release and examples in [Basic API reference](https://mrmustard.readthedocs.io/en/latest/introduction/basic_reference.html) of readthedocs are outdated.
This PR updates the examples and documentation which are already updated in Mr Mustard's README.
**Benefits:**
Up-to-date docs.
> Update basic API reference 

- .github/CHANGELOG.md
- README.md
- mrmustard/_version.py
- setup.py
Releasing a new version of Mr Mustard.
* Support for Python 3.10
* Version bumped to 0.2.0
* Added changelog entries.
> Incrementing the version number to 0.2.0

- .github/CHANGELOG.md
- README.md
- mrmustard/_version.py
Mr Mustard has been released! 🎩
> Incrementing the version number to 0.3.0-dev

- mrmustard/lab/abstract/state.py
fixes a typo that was causing an error
> fixes dm typo

- .github/CHANGELOG.md
- tests/test_lab/test_states.py
we are adding a test for the bug fix in #135, and we are updating the changelog
> updates changelog

- mrmustard/lab/gates.py
- tests/test_lab/test_gates_fock.py
Fixes a typo that prevented channels from being applied to Fock states
Closes #151
> fixed is_unitary typo

- .github/workflows/tests.yml
- requirements.txt
**Context:**
New versions of numpy, numba and tensorflow have been released. Codecov action v1 has been deprecated. 
Upgrades requirements.
**Benefits:**
Up to date requirements.
> Upgrade requirements to latest

- .github/CHANGELOG.md
- mrmustard/_version.py
Preparing for the release of Mr Mustard v0.3.0
> Incrementing the version number to v0.3.0

- .github/workflows/upload.yml
> Fix indentation on release action yaml

- .github/CHANGELOG.md
- mrmustard/_version.py
Mr Mustard v0.3.0 has been released! 🚀
> Incrementing version number to 0.4.0-dev

- mrmustard/lab/gates.py
- mrmustard/math/math_interface.py
- mrmustard/math/tensorflow.py
- tests/test_lab/test_detectors.py
**Context:**
There was a bug in the gradient computation of the Gate
Bug is fixed (there was a numpy array at some point that was breaking the chain rule)
**Benefits:**
It works
None
None
> Bugfix dgate gradient

- .github/CHANGELOG.md
- mrmustard/utils/graphics.py
- tests/test_utils/test_graphics.py
**Context:**
Currently marginals are calculated form the Wigner function. In cases in which not all features of the state are captured on the Wigner function, the marginals contain negativities hence not representing a true probability density.
This PR makes `mikkel_plot` 
- calculate marginals independently from the Wigner function thus ensuring that the marginals are physical even though the Wigner function might not contain all the features of the state within the defined window,
- expose the `ticks`, `tick_labels` and `grid` arguments to customize the visualization — useful for example when checking that your state has peaks in those dreaded multiples of √(π)
- return the figure and axes for further processing if needed
**Benefits:**
- Marginals in the …
> Use marginal distribution when drawing 🎨

- mrmustard/lab/abstract/transformation.py
- mrmustard/physics/fock.py
- tests/test_physics/test_fock/test_fock.py
**Context:**
The application of a choi operator to a density matrix was resulting in a transposed dm
Fixes the order of the indices in the application of a choi operator to dm and ket
**Benefits:**
Correct result
None
None
> Choi application bugfix

- .github/CHANGELOG.md
- mrmustard/lab/abstract/transformation.py
- mrmustard/physics/fock.py
- tests/test_lab/test_gates_fock.py
- tests/test_physics/test_fock/test_fock.py
**Context:**
Fixes a few bugs related to transformation of states in Fock representation
- adds missing default argument 
- adds a function for convenience
- fixes a bug due to old code not removed in `Transformation.transform_fock`
- adds 11 tests to avoid same type of bug
- adds 2 parametrized tests (10 in total) to check correct application of unitaries and channels to kets and dm in Fock representation
**Benefits:**
Correct code
None
No issue but FTB simulation not running on develop branch
> Bugfix axis labels

- .github/CHANGELOG.md
- mrmustard/physics/bargmann.py
- mrmustard/physics/fock.py
**Context:**
Fixing a bug related to tensorflow not liking products of complex128 and float64
cast where necessary
**Benefits:**
Code that runs
None
None
> Bugfix typerror

- .github/CHANGELOG.md
- .github/workflows/tests.yml
- tests/test_training/test_trainer.py
**Context:**
Attempt to fix the (random) never ending tests on github actions.
I have so far rerun the test 5 times without the issue reoccurring. 🤞 
Forces ray to init with 1 cpu for testing.
**Benefits:**
> ray test fix

- .github/CHANGELOG.md
- mrmustard/_version.py
**Context:**
v0.4 release
shortened long lines and fixed some typos
**Benefits:**
good changelog
None
None
> Bump version and get changelog ready for release

- .github/CHANGELOG.md
- mrmustard/_version.py
Incrementing version to 0.5.0-dev
> Increment version to 0.5.0-dev

- .github/CHANGELOG.md
- mrmustard/physics/gaussian.py
- requirements.txt
- tests/random.py
- tests/test_math/test_compactFock.py
- tests/test_physics/test_fidelity.py
- tests/test_training/test_opt.py
- tests/test_training/test_riemannian_opt.py
**Context:**
One of the tests for the RealInterferometer optimization was flaky
Fix the test by starting from a perturbed solution
**Benefits:**
Always works
none
none
> fix flaky test

- .github/CHANGELOG.md
- mrmustard/physics/fock.py
- tests/test_training/test_opt.py
duplicate PR as #230, but toward the `main` branch instead of `develop`
> fix and test

- .github/CHANGELOG.md
- tests/test_lab/test_gates_fock.py
- tests/test_math/test_compactFock.py
**Context:**
Fix 2 more flaky tests
played with cutoffs and cost function
**Benefits:**
hopefully more consistent tests
none
none
> Fix more flaky 0.4.1

- .github/CHANGELOG.md
- mrmustard/physics/fock.py
- tests/test_physics/test_fock/test_fock.py
**Context:** The input variable in the function apply_choi_to_dm is not correct
**Description of the Change:** from choi_in_idx to choi_in_modes
**Benefits:**
> fix the variable name in apply choi

- .github/CHANGELOG.md
- mrmustard/lab/abstract/transformation.py
- mrmustard/lab/gates.py
- Added `shape` (see changelog)
- Removed `bargman` method in transformation
> Fixing bug in develop

- .github/CHANGELOG.md
- mrmustard/utils/settings.py
- tests/test_math/test_compactFock.py
- tests/test_math/test_lattice.py
Skipping Julia tests if Julia is not installed.
These tests are still run by GitHub
> Skipping Julia tests if Julia is not installed.

- mrmustard/math/backend_manager.py
BackendManager is a singleton. As such, we can replace many of its `cls` to `self`
> Cleaning up the backend manager

- tests/test_lab/test_state.py
**Context:** The tests failed sometimes because of the cutoff=1.
**Description of the Change:** Add cutoff 10 for all states.
**Benefits:**
> Add cutoff for states in test_state

- .github/CHANGELOG.md
- pyproject.toml
**Context:**
There is a mismatch of tags, this reconciles
> Reconciling versions

- mrmustard/lab_dev/circuit_components.py
An `isinstance` check fails on some machines. Hopefully this fixes it.
> fixed isinstance check

- .github/CHANGELOG.md
- poetry.lock
- pyproject.toml
https://open.spotify.com/track/0qGQXQdUNwPYQadGuELgEI?si=a00585ac1b99477e
> only bound thelwarus by major version

- mrmustard/physics/gaussian_integrals.py
- tests/test_physics/test_gaussian_integrals.py
Fixes bug by reshaping some parts of a product correctly
___
Bug fix, Tests
___
- Fixed a broadcasting bug in the `complex_gaussian_integral_1` function by reshaping the computed `c_post` to match the shape of `c`.
- Added a new test case to ensure the Gaussian integral function works correctly with batched inputs and polynomial `c`, verifying the output shapes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>gaussian_integrals.py</strong><dd><code>Fix broadcasting issue in Gaussian integral calculation</code>&nbsp; &nbsp; </dd></summary>
<hr>
mrmustard/physics/gaussian_integrals.py
<li>Fixed broadcasting issue in the calculation of <code>c_post</code>.<br> <li> …
> Bugfix: c broadcasting in gaussian integral

- mrmustard/physics/ansatz/polyexp_ansatz.py
einsum strings cannot have spaces, otherwise opt_einsum can't figure it out.
> fixed einsum string
